---
- name: Configure ssh on nodes
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes 
  gather_facts: no

  tasks:
    - name: Make PasswordAuthentication yes
      replace:
         path: /etc/ssh/sshd_config
         regexp: 'PasswordAuthentication no'
         replace: 'PasswordAuthentication yes'
      notify: restart sshd service

  handlers:
    - name: restart sshd service
      service:
        name: sshd
        state: restarted
        enabled: yes
